name: Cron

on:
  schedule:
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  mkdir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - uses: actions/checkout@v2
      - run: go run github.com/Shivam010/daily-coding-problem/cmd
        env:
          cron: true # setup a new problem directory & update readme
      - run: |
          git config user.name "Shivam Rathore"
          git config user.email shivam.rathore010@gmail.com
          git status
          git add .
          git commit -m "Setup new problem directory" || echo "Ignoring nothing to commit"
          git push
